### ISSUE TITLE
compatibility of openff-2.1.0 and Amber 99SB-disp ff

### ISSUE THREAD

**Issue by 8marmar8** [openforcefield/discussions#31]
Hi,
I would like to simulate a disordered protein in complex with a small molecule. I have already obtained the OpenFF-2.1.0 parameters for the small molecule for Gromacs. I noticed that the recommended Amber force field for proteins in combination with the OpenFF-2.1.0 for the ligand is AMBER ff99sb-ILDN*, but this one is not optimized for disordered proteins. Therefore, I would like to know if I can use the OpenFF-2.1.0 parameters for the small molecule in combination with the Amber 99SB-disp force field, which is suitable for simulating disordered proteins.

Thank you

**Comment by j-wags** [comment]
Hi @8marmar8,

I think the Parsley and Sage force fields are in principle compatible with most AMBER protein force fields - Both FF lines were trained mostly to QM targets using comparable levels of theory. We haven't done any validation/testing of Sage with AMBER 99-disp but I don't think it's an unreasonable combination. 

> I noticed that the recommended Amber force field for proteins in combination with the OpenFF-2.1.0 for the ligand is AMBER ff99sb-ILDN*

I'm curious where you saw this recommendation - generally we put together examples using AMBER ff14SB because it's the most recent one that we could port into the SMIRNOFF format (ff19 had some technical incompatibilities at the time). Someone may have good reasons for suggesting a Sage/ff99 pairing but I'm unaware of that argument - I'd expect newer AMBER FF lines to have improved accuracy (though in the case of specific domains like disordered proteins something like 99-disp makes sense).

**Comment by davidlmobley** [comment]
I'd comment that there's been very little research (if any?) on what "compatibility" means with respect to protein and small molecule force fields, and I think we have carefully avoided making any firm recommendations for exactly that reason. Some of the AMBER devs have said something informally to us along the lines of "compatibility is overrated" but I think this is pretty much an area of unexplored science. Personally I'd be comfortable using OpenFF with typical AMBER family protein force fields for now, but that's up to you and I believe unexplored.

**Comment by 8marmar8** [comment]
Thank you @j-wags and @davidlmobley for your quick response. 

Regarding the suggestion of using the AMBER ff99sb-ILDN* force field, I found this recommendation in a recent article: [https://doi.org/10.1021/acs.jctc.3c00039]. However, I also previously read your suggestion to use the AMBER ff14SB force field.

Regarding my uncertainty about whether to use the Amber 99SB-disp force field, it's precisely because I'm working with an intrinsically disordered protein and I need to analyze its behavior in complex with a molecule. Therefore, I require an accurate force field for the protein as well. I haven't come across any recommendations for using AMBER ff14SB with intrinsically disordered proteins.

**Comment by j-wags** [comment]
Ahh, there must have been a technical reason at the time for using ff99. Thanks for asking a great question - FF compatibility is tricky and others would probably find this discussion useful. I'm going to move this issue to our "Discussions" repo for discoverability.
